services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n:/home/node/.n8n
    environment:
      GENERIC_TIMEZONE: America/Sao_Paulo
    restart: unless-stopped
    networks:
      - n8n-network

  waha:
    image: devlikeapro/waha
    ports:
      - "3000:3000"
    volumes:
      - ./waha:/tmp
    environment:
      WHATSAPP_DEFAULT_ENGINE: NOWEB
      WHATSAPP_HOOK_EVENTS: message
      WHATSAPP_HOOK_URL: http://host.docker.internal:5678/webhook/94403545-bcce-4e83-ba80-4798353cd599/waha  # URL interna via network
      WAHA_NO_API_KEY: "true"
      WAHA_DASHBOARD_NO_PASSWORD: "true"
      WHATSAPP_SWAGGER_NO_PASSWORD: "true"
    restart: unless-stopped
    networks:
      - n8n-network

networks:
  n8n-network:
    driver: bridge